class MONITOR_CHART_NAMES:
    TARGET = 'TGT'
    SOURCE = 'SRC'
    VOLUMES = 'TGTVOLS'
    TGT_BID = 'TGTBID'
    TGT_ASK = 'TGTASK'


class INDICATOR_NAMES:
    SIMPLE = 'IND_SIMPLE'
    WEIGTHED = 'IND_WEIGHTED'


class DECISIONS:
    BUY_ALL = 'BUY_ALL'
    SELL_ALL = 'SELL_ALL'
    AMBIGUOUS = 'AMBIGUOUS'
    NO_DATA = 'NO_DATA'
